version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 3
    labels:
      - 'dependencies'
      - 'javascript'
    groups:
      dev-deps:
        dependency-type: 'development'
      deps:
        dependency-type: 'production'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 3
    labels:
      - 'ci'
      - 'dependencies'
      - 'github-actions'
    groups:
      actions:
        patterns:
          - '*'
    commit-message:
      prefix: 'ci'
      include: 'scope'
